# 예외

- 예외를 처리하기 위해 사용하는 방법



## try... catch.. finally

- 예외에서 핵심적인 역할을 담당하는 문법적 요소

```java
try{
  예외의 발생이 예상되는 로직
} catch(예외 클래스 인스턴스){
  예외가 발생되었을때 실행되는 로직
} finally{
  // finally는 optional
  예외 여부와 관계없이 실행되는 로직
}
```

- try 안에는 예외 상황이 발생할 것으로 예상되는 로직 위치시킴
- catch 안에는 예외가 발생했을 때 뒷수습을 하기위한 로직이 위치 
  - 다중 catch문 사용 가능

```java
// e는 변수
// Exception은 변수의 데이터 타입 의미 (자바에서 기본적으로 제공하는 클래스)
} catch(Exception e){
  
}
```



## 뒷수습 방법

- `Exception e` 로 예외를 처리할 경우 기본 메소드
  - `e.getMessage()` 
    - 오류에 대한 기본적인 내용 출력
  - `e.toString()`
    - `e.getMessage()` 보다 더 자세한 예외 정보 제공
  - `e.printStackTrace()`
    - 리턴 값이 따로 없음
    - 메소드가 내부적으로 예외 결과를 화면에 출력
    - 가장 자세한 예외 정보를 제공



## throw와 throws

- throw 현재 메소드 내에서 예외를 강제로 발생시키거나 현재 메소드에게 exception 정보를 전달 가능

  - 메소드를 발생시켜 메서드 내에서 예외 처리

  - throw 뒤에는 예외 정보를 가지고 있는 예외 클래스가 위치 함
    - 이 클래스를 기준으로 예외 상황의 원인에 대한 정보를 알 수 있음

- throw와 throws는 예외처리를 다음 사용자에게 넘기는 것

  - 현재 메서드에서 자신을 호출한 상위 메소드로 Exception을 발생시킴





## 출처

> https://opentutorials.org/module/516/6226
>
> https://opentutorials.org/module/516/6227
>
> https://opentutorials.org/module/516/6228